### ISSUE TITLE
Show nested teams 

### ISSUE THREAD

**Issue by dberesford** [nearform/udaru-ui-admin#3]
A team can consist of users and sub-teams, need to show the sub teams and the ability to navigate in to them

**Comment by jimmymintzer** [comment]
I am not sure this is possible without adding a new endpoint. If I hit `/authorization/teams` then it returns that page of teams (say the first 5 if I use this query`?page=1&limit=5`). That list contains all teams whether they are nested teams or root level teams. To determine if it's a nested team, you can look at the `path` and if it contains a dot, then it's a nested team like:

```js
{
  "id": "8",
  "name": "Children Team",
  "description": "This is a children team.",
  "path": "7.8",
  "organizationId": "WONKA",
  "usersCount": 0
}
```

This means there is no way to determine if the parent team has children since that object would look like:

```js
{
  "id": "7",
  "name": "Parent Team",
  "description": "This is a parent team.",
  "path": "7",
  "organizationId": "WONKA",
  "usersCount": 0
}
```

The only way to determine would be to check every team and see if there are nested sub teams which isn't possible since the results are paginated and it wouldn't be practical client side with a large data set.

**Comment by jimmymintzer** [comment]
PR has been merged into Udaru, closing this issue
